Listen 80

LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule alias_module modules/mod_alias.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule cgi_module modules/mod_cgi.so

ServerName localhost

User www-data
Group www-data

DocumentRoot "/usr/local/apache2/htdocs"

<Directory />
    Require all denied
</Directory>

ScriptAlias /api/ "/srv/api/"

<Directory "/srv/api">
    Options +ExecCGI
    Require all granted
</Directory>
